version: '3.8'
services:

  frontend:
    container_name: "frontend"
    image: allenokech/frontend
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      DATABASE_URI: $(DATABASE_URI)
  
  service2:
    container_name: "service2"
    image: allenokech/service2
    build: ./service2
    deploy:
      replicas: 3
  
  service3:
    container_name: "service3"
    image: allenokech/service3
    build: ./service3
    deploy:
      replicas: 3

  service4:
    container_name: "service4"
    image: allenokech/service4
    build: ./service4
    deploy:
      replicas: 3
  
  