- name: Init Docker Swarm 
  hosts: managers
  become: true
  roles:
    - docker
    - swarm-init

- name: Adding Workers to Swarm
  hosts: workers
  become: true
  roles: 
    - docker
    - swarm-worker
    - nginx